include: package:pedantic/analysis_options.yaml

analyzer:
  enable-experiment:
    - extension-methods
  exclude:
    - "lib/generated/"
    - "lib/generated/**"
    - "lib/generated/l10n.dart"
    - "**/*.g.dart"

linter:
  rules:
    prefer_single_quotes: false