name: app2heaven_flutter
description: A new Flutter application.

version: 3.2.2+9900103 # This is only for Android, iOS uses the version from Xcode

environment:
  sdk: '>=2.12.0 <3.0.0'

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  archive: ^3.1.2
  audio_service: ^0.18.0
  fl_chart: ^0.40.0
  cloud_firestore: ^2.5.3
  datetime_picker_formfield: ^2.0.0
  device_info: ^2.0.0
  devicelocale: ^0.5.0
  feature_discovery: ^0.14.0
  file_picker_cross: ^4.5.0
  firebase_analytics: ^8.0.0
  firebase_core: ^1.0.2
  firebase_crashlytics: ^2.0.0
  firebase_dynamic_links: ^2.0.0
  firebase_in_app_messaging: ^0.5.0+9
  firebase_installations: ^16.3.6
  firebase_messaging: ^10.0.0
  flutter_local_notifications: ^9.0.0
  flutter_markdown: ^0.6.1
  flutter_native_timezone: ^2.0.0
  flutter_phoenix: ^1.0.0
  flutter_secure_storage: ^4.1.0
  flutter_typeahead: ^3.1.1
  http: ^0.13.1
  intl: ^0.17.0
  intl_utils: ^2.1.0
  just_audio: ^0.9.12
  moor: ^4.2.1
  package_info_plus: ^1.3.0
  page_view_indicators: ^2.0.0
  path: ^1.8.0
  path_provider: ^2.0.1
  pointycastle: ^3.0.1
  provider: ^5.0.0
  rxdart: ^0.27.0
  selectable_autolink_text: ^2.3.0
  share: ^2.0.1
  sqlite3_flutter_libs: ^0.5.0
  streaming_shared_preferences: ^2.0.0
  timer_builder: ^2.0.0
  timezone: ^0.8.0
  uni_links: ^0.5.0
  url_launcher: ^6.0.3
  webview_flutter: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.1
  moor_generator: ^4.2.1
  pedantic: ^1.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/sidemenu/
    - assets/deeds/
    - assets/decisions/
    - assets/gods_words/
    - assets/gods_words/reminders/
    - assets/gods_words/open_bible/
    - assets/prayer_requests/
    - assets/prayer_times/
    - assets/experiences/
    - assets/confession/
    - assets/bible/

  fonts:
    - family: RatingsIcons
      fonts:
        - asset: fonts/ratings_icons.ttf

flutter_intl:
  enabled: true
